UPDATE Producto SET Nombre = 'SUAVIZANTE CONF VERDE QUERU', Detalle = '', Precio = '25.00', IDCategoria = '2', CodLimpiadin = '642' WHERE ID = '562';
UPDATE Producto SET Nombre = 'TERMO ALFA LUMILAGRO', Detalle = '', Precio = '429.00', IDCategoria = '9', CodLimpiadin = '511' WHERE ID = '574';
UPDATE Producto SET Nombre = 'TERMO BOCA LUMILAGRO', Detalle = '', Precio = '577.50', IDCategoria = '9', CodLimpiadin = '510' WHERE ID = '575';
UPDATE Producto SET Nombre = 'TERMO OLIMPICO', Detalle = '', Precio = '561.00', IDCategoria = '9', CodLimpiadin = '363' WHERE ID = '576';
UPDATE Producto SET Nombre = 'TERMO PANDA CON BOMBA LUMILAGRO', Detalle = '', Precio = '1200.00', IDCategoria = '9', CodLimpiadin = '623' WHERE ID = '577';
UPDATE Producto SET Nombre = 'TERMO RIVER LUMILAGRO', Detalle = '', Precio = '577.50', IDCategoria = '9', CodLimpiadin = '509' WHERE ID = '578';
UPDATE Producto SET Nombre = 'TERMO SIGMA LUMILAGRO', Detalle = '', Precio = '569.50', IDCategoria = '9', CodLimpiadin = '512' WHERE ID = '579';
UPDATE Producto SET Nombre = 'TERMO SUPER TERMICA LUMILAGRO', Detalle = '', Precio = '459.00', IDCategoria = '9', CodLimpiadin = '526' WHERE ID = '580';
UPDATE Producto SET Nombre = 'TIJERA PUNTO ROJO', Detalle = '', Precio = '165.00', IDCategoria = '9', CodLimpiadin = '702' WHERE ID = '581';
UPDATE Producto SET Nombre = 'TENEDOR CAROL PLAST X UNIDAD', Detalle = '', Precio = '44.20', IDCategoria = '9', CodLimpiadin = '258' WHERE ID = '573';
UPDATE Producto SET Nombre = 'TENDER RED 12 BROCHES GRANDE', Detalle = '', Precio = '202.50', IDCategoria = '9', CodLimpiadin = '675' WHERE ID = '572';
UPDATE Producto SET Nombre = 'TENDER 6 BROCHES CHICO', Detalle = '', Precio = '102.00', IDCategoria = '9', CodLimpiadin = '285' WHERE ID = '571';
UPDATE Producto SET Nombre = 'SUAVIZANTE CONI', Detalle = '', Precio = '29.00', IDCategoria = '2', CodLimpiadin = '15' WHERE ID = '563';
UPDATE Producto SET Nombre = 'SUAVIZANTE DEDITOS FUCSIA', Detalle = '', Precio = '25.00', IDCategoria = '2', CodLimpiadin = '17' WHERE ID = '564';
UPDATE Producto SET Nombre = 'SUAVIZANTE VIV CELESTE ', Detalle = '', Precio = '29.00', IDCategoria = '2', CodLimpiadin = '16' WHERE ID = '565';
UPDATE Producto SET Nombre = 'TAZON AMANECER', Detalle = '', Precio = '93.00', IDCategoria = '9', CodLimpiadin = '681' WHERE ID = '566';
UPDATE Producto SET Nombre = 'TELA MEDIA SOMBRA 90%', Detalle = '', Precio = '420.00', IDCategoria = '9', CodLimpiadin = '685' WHERE ID = '567';
UPDATE Producto SET Nombre = 'TELA MEDIA SOMBRA 98%', Detalle = '', Precio = '510.00', IDCategoria = '9', CodLimpiadin = '686' WHERE ID = '568';
UPDATE Producto SET Nombre = 'TENDEDERO CAÑO C/ ALAS SOGA', Detalle = '', Precio = '1224.00', IDCategoria = '9', CodLimpiadin = '304' WHERE ID = '569';
UPDATE Producto SET Nombre = 'TENDEDERO DE ALUMINIO SIN ALAS', Detalle = '', Precio = '1898.00', IDCategoria = '9', CodLimpiadin = '641' WHERE ID = '570';
UPDATE Producto SET Nombre = 'TOALLA INTERCALADA BLANCA', Detalle = '', Precio = '720.00', IDCategoria = '7', CodLimpiadin = '593' WHERE ID = '582';
UPDATE Producto SET Nombre = 'TRAPO DE PISO BLANCO', Detalle = '', Precio = '55.50', IDCategoria = '4', CodLimpiadin = '147' WHERE ID = '583';
UPDATE Producto SET Nombre = 'TRAPO DE PISO GRIS', Detalle = '', Precio = '43.50', IDCategoria = '4', CodLimpiadin = '146' WHERE ID = '584';
UPDATE Producto SET Nombre = 'VASO VID NOBILE LISO UNIDAD ', Detalle = '', Precio = '28.90', IDCategoria = '9', CodLimpiadin = '325' WHERE ID = '596';
UPDATE Producto SET Nombre = 'VELAS CHICAS EL ARRIERO', Detalle = '', Precio = '22.50', IDCategoria = '9', CodLimpiadin = '205' WHERE ID = '597';
UPDATE Producto SET Nombre = 'VELAS GRANDES EL ARRIERO', Detalle = '', Precio = '45.00', IDCategoria = '9', CodLimpiadin = '223' WHERE ID = '598';
UPDATE Producto SET Nombre = 'VENUS 3 MAQUINA DE AFEITAR SUMPLY ', Detalle = '', Precio = '49.00', IDCategoria = '9', CodLimpiadin = '433' WHERE ID = '599';
UPDATE Producto SET Nombre = 'VERTEDOR DOBLE 1 KG YESI', Detalle = '', Precio = '89.40', IDCategoria = '9', CodLimpiadin = '537' WHERE ID = '600';
UPDATE Producto SET Nombre = 'VERTEDOR PLAST YERBA / AZUCAR 550CC', Detalle = '', Precio = '44.20', IDCategoria = '9', CodLimpiadin = '319' WHERE ID = '601';
UPDATE Producto SET Nombre = 'VIRULANA MARCA OK  X 12 UNID', Detalle = '', Precio = '36.00', IDCategoria = '4', CodLimpiadin = '162' WHERE ID = '602';
UPDATE Producto SET Nombre = 'XMART  MAQUINA DE AFEITAR 3 HOJAS', Detalle = '', Precio = '52.50', IDCategoria = '7', CodLimpiadin = '495' WHERE ID = '603';
UPDATE Producto SET Nombre = 'VASO PLASTICO INDYGO 475CC', Detalle = '', Precio = '13.20', IDCategoria = '9', CodLimpiadin = '320' WHERE ID = '595';
UPDATE Producto SET Nombre = 'VASO PLASTICO BONGO NIÑO ', Detalle = '', Precio = '48.00', IDCategoria = '9', CodLimpiadin = '690' WHERE ID = '594';
UPDATE Producto SET Nombre = 'VASO PINTA CERV 540ML', Detalle = '', Precio = '117.00', IDCategoria = '9', CodLimpiadin = '513' WHERE ID = '593';
UPDATE Producto SET Nombre = 'UVA-CHICLE DESODORANTE P/PISOS', Detalle = '', Precio = '28.00', IDCategoria = '5', CodLimpiadin = '679' WHERE ID = '585';
UPDATE Producto SET Nombre = 'VASO CAIRO', Detalle = '', Precio = '49.92', IDCategoria = '9', CodLimpiadin = '657' WHERE ID = '586';
UPDATE Producto SET Nombre = 'VASO COCA COLA ', Detalle = '', Precio = '75.00', IDCategoria = '9', CodLimpiadin = '656' WHERE ID = '587';
UPDATE Producto SET Nombre = 'VASO DE VIDRIO IRUPE', Detalle = '', Precio = '49.30', IDCategoria = '9', CodLimpiadin = '291' WHERE ID = '588';
UPDATE Producto SET Nombre = 'VASO DE VIDRIO MONTECARLO', Detalle = '', Precio = '49.30', IDCategoria = '9', CodLimpiadin = '356' WHERE ID = '589';
UPDATE Producto SET Nombre = 'VASO DE VIDRIO NAHUEL MERCATOR', Detalle = '', Precio = '49.30', IDCategoria = '9', CodLimpiadin = '290' WHERE ID = '590';
UPDATE Producto SET Nombre = 'VASO ECONOMICO X 6 UNID', Detalle = '', Precio = '114.00', IDCategoria = '9', CodLimpiadin = '639' WHERE ID = '591';
UPDATE Producto SET Nombre = 'VASO MEDIDOR X 1 LT', Detalle = '', Precio = '57.00', IDCategoria = '9', CodLimpiadin = '192' WHERE ID = '592';
UPDATE Producto SET Nombre = 'ZORRO DETERGENTE X 300 ML', Detalle = '', Precio = '60.00', IDCategoria = '5', CodLimpiadin = '525' WHERE ID = '604';
UPDATE Producto SET Nombre = 'SUAVIZANTE CONF ROSADO', Detalle = '', Precio = '25.00', IDCategoria = '2', CodLimpiadin = '13' WHERE ID = '561';
UPDATE Producto SET Nombre = 'MASAJEADOR CON USB', Detalle = '', Precio = '120.00', IDCategoria = '10', CodLimpiadin = '520' WHERE ID = '389';
UPDATE Producto SET Nombre = 'SECADOR DE GOMA ROJA X 40 CM', Detalle = '', Precio = '120.00', IDCategoria = '4', CodLimpiadin = '151' WHERE ID = '530';
UPDATE Producto SET Nombre = 'SEDAL ACONDICIONADOR X 10 ML', Detalle = '', Precio = '9.90', IDCategoria = '7', CodLimpiadin = '582' WHERE ID = '531';
UPDATE Producto SET Nombre = 'SEDAL SHAMPOO SACHET X 10 ML', Detalle = '', Precio = '9.90', IDCategoria = '7', CodLimpiadin = '581' WHERE ID = '532';
UPDATE Producto SET Nombre = 'SET DE MANICURA ', Detalle = '', Precio = '150.00', IDCategoria = '7', CodLimpiadin = '522' WHERE ID = '533';
UPDATE Producto SET Nombre = 'SET MATERO ENCASTRABLE  CROM', Detalle = '', Precio = '160.00', IDCategoria = '9', CodLimpiadin = '276' WHERE ID = '534';
UPDATE Producto SET Nombre = 'SET MATERO FORRA 2 VERT PLAST + MATE  CON', Detalle = '', Precio = '374.00', IDCategoria = '9', CodLimpiadin = '347' WHERE ID = '535';
UPDATE Producto SET Nombre = 'SET SALERO PIMIENTERO X 4 UNID ACERO INOXBOLSA ', Detalle = '', Precio = '750.00', IDCategoria = '9', CodLimpiadin = '635' WHERE ID = '536';
UPDATE Producto SET Nombre = 'SHAMPOO PANTENNE', Detalle = '', Precio = '35.00', IDCategoria = '7', CodLimpiadin = '40' WHERE ID = '537';
UPDATE Producto SET Nombre = 'SECADOR DE GOMA ROJA X 30 CM', Detalle = '', Precio = '93.00', IDCategoria = '4', CodLimpiadin = '189' WHERE ID = '529';
UPDATE Producto SET Nombre = 'SECADOR DE GOMA NEGRA X 40 CM', Detalle = '', Precio = '94.50', IDCategoria = '4', CodLimpiadin = '150' WHERE ID = '528';
UPDATE Producto SET Nombre = 'SECADOR DE GOMA NEGRA X 30 CM', Detalle = '', Precio = '81.00', IDCategoria = '4', CodLimpiadin = '149' WHERE ID = '527';
UPDATE Producto SET Nombre = 'PILA EVEREADY AA X 4 UNID', Detalle = '', Precio = '78.00', IDCategoria = '10', CodLimpiadin = '423' WHERE ID = '463';
UPDATE Producto SET Nombre = 'PILA EVEREADY AAA X 4 UNID', Detalle = '', Precio = '62.90', IDCategoria = '10', CodLimpiadin = '424' WHERE ID = '464';
UPDATE Producto SET Nombre = 'SAHUMERIO GOVINDA', Detalle = '', Precio = '51.00', IDCategoria = '9', CodLimpiadin = '633' WHERE ID = '521';
UPDATE Producto SET Nombre = 'SALERO-PIMIENT  PORCELANA RED', Detalle = '', Precio = '187.00', IDCategoria = '9', CodLimpiadin = '277' WHERE ID = '522';
UPDATE Producto SET Nombre = 'SANITIZANTE X 250 ML SAPHIRUS', Detalle = '', Precio = '159.00', IDCategoria = '7', CodLimpiadin = '573' WHERE ID = '523';
UPDATE Producto SET Nombre = 'SANITIZANTE X 500 ML SAPHIRUS', Detalle = '', Precio = '234.00', IDCategoria = '7', CodLimpiadin = '574' WHERE ID = '524';
UPDATE Producto SET Nombre = 'SAPITO PARA RIEGO', Detalle = '', Precio = '60.00', IDCategoria = '9', CodLimpiadin = '676' WHERE ID = '525';
UPDATE Producto SET Nombre = 'SECADOR DE DOBLE GOMA DE 40 CM', Detalle = '', Precio = '105.00', IDCategoria = '4', CodLimpiadin = '220' WHERE ID = '526';
UPDATE Producto SET Nombre = 'SHAMPOO PARA AUTO TUTI FRUTTI', Detalle = '', Precio = '34.00', IDCategoria = '2', CodLimpiadin = '52' WHERE ID = '538';
UPDATE Producto SET Nombre = 'SHAMPOO PARA MASCOTA', Detalle = '', Precio = '33.00', IDCategoria = '2', CodLimpiadin = '35' WHERE ID = '539';
UPDATE Producto SET Nombre = 'SHAMPOO SEDDAL', Detalle = '', Precio = '35.00', IDCategoria = '7', CodLimpiadin = '491' WHERE ID = '540';
UPDATE Producto SET Nombre = 'SODA CAUSTICA LÍQUIDA', Detalle = '', Precio = '54.00', IDCategoria = '2', CodLimpiadin = '33' WHERE ID = '552';
UPDATE Producto SET Nombre = 'SOPAPA FUELLE', Detalle = '', Precio = '82.50', IDCategoria = '4', CodLimpiadin = '436' WHERE ID = '553';
UPDATE Producto SET Nombre = 'SOPAPA GOMA NEGRA', Detalle = '', Precio = '45.00', IDCategoria = '4', CodLimpiadin = '148' WHERE ID = '554';
UPDATE Producto SET Nombre = 'SOPAPA ROJA ', Detalle = '', Precio = '52.50', IDCategoria = '4', CodLimpiadin = '360' WHERE ID = '555';
UPDATE Producto SET Nombre = 'SUAVE JABON DE TOCADOR X 125GR', Detalle = '', Precio = '30.00', IDCategoria = '7', CodLimpiadin = '455' WHERE ID = '556';
UPDATE Producto SET Nombre = 'SUAVE SHAMPOO X 930 ML', Detalle = '', Precio = '117.00', IDCategoria = '7', CodLimpiadin = '480' WHERE ID = '557';
UPDATE Producto SET Nombre = 'SUAVIZANTE CONF AMARILLO', Detalle = '', Precio = '29.00', IDCategoria = '2', CodLimpiadin = '86' WHERE ID = '558';
UPDATE Producto SET Nombre = 'SUAVIZANTE CONF BLANCO', Detalle = '', Precio = '25.00', IDCategoria = '2', CodLimpiadin = '14' WHERE ID = '559';
UPDATE Producto SET Nombre = 'SKI ECO JABON LIQUIDO', Detalle = '', Precio = '23.00', IDCategoria = '2', CodLimpiadin = '531' WHERE ID = '551';
UPDATE Producto SET Nombre = 'SK JABON LIQUIDO CONCENTRADO', Detalle = '', Precio = '34.00', IDCategoria = '2', CodLimpiadin = '2' WHERE ID = '550';
UPDATE Producto SET Nombre = 'SINA BARREDOR DOMESTICO 35 CM', Detalle = '', Precio = '300.00', IDCategoria = '10', CodLimpiadin = '680' WHERE ID = '549';
UPDATE Producto SET Nombre = 'SHELTON INSECTICIDA ', Detalle = '', Precio = '141.00', IDCategoria = '6', CodLimpiadin = '397' WHERE ID = '541';
UPDATE Producto SET Nombre = 'SIGNO JABON EN PAN X 200 GR', Detalle = '', Precio = '34.50', IDCategoria = '5', CodLimpiadin = '603' WHERE ID = '542';
UPDATE Producto SET Nombre = 'SIGNO X 150 GRS JABON EN PAN  ', Detalle = '', Precio = '25.50', IDCategoria = '5', CodLimpiadin = '440' WHERE ID = '543';
UPDATE Producto SET Nombre = 'SIGNO X 3 UNID TOCADOR', Detalle = '', Precio = '58.50', IDCategoria = '5', CodLimpiadin = '602' WHERE ID = '544';
UPDATE Producto SET Nombre = 'SILICONA EMULSIONADA', Detalle = '', Precio = '59.00', IDCategoria = '2', CodLimpiadin = '53' WHERE ID = '545';
UPDATE Producto SET Nombre = 'SILICONA EN AEROSOL EL SALVADOR', Detalle = '', Precio = '135.15', IDCategoria = '5', CodLimpiadin = '337' WHERE ID = '546';
UPDATE Producto SET Nombre = 'SILICONA SOLVENTADA', Detalle = '', Precio = '199.00', IDCategoria = '2', CodLimpiadin = '54' WHERE ID = '547';
UPDATE Producto SET Nombre = 'SILLA REINA NEGRA', Detalle = '', Precio = '697.50', IDCategoria = '9', CodLimpiadin = '643' WHERE ID = '548';
UPDATE Producto SET Nombre = 'SUAVIZANTE CONF CELESTE', Detalle = '', Precio = '25.00', IDCategoria = '2', CodLimpiadin = '11' WHERE ID = '560';
